
import java.awt.Image;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author DELL
 */
public final class Add_Purchase extends javax.swing.JFrame {

    /**
     * Creates new form Add_Purchase
     */
    public Add_Purchase() {
       
        initComponents();
        
        Image icon = new ImageIcon(this.getClass().getResource("/icon.png")).getImage();
        this.setIconImage(icon);
        
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy/MM/dd");
        Date d = new Date();
        date_lbl.setText(sdf.format(d));
    
        cbLoadData("distributor","name", jComboBox1);
        AutoCompleteDecorator.decorate(jComboBox1);
        
        cbLoadData("brand","name", jComboBox2);
        AutoCompleteDecorator.decorate(jComboBox2);
        
        cbLoadData("model","name", jComboBox3);
        AutoCompleteDecorator.decorate(jComboBox3);
        
        try {
            ResultSet rs = dbcon.SEARCH("SELECT `id` FROM purchase ORDER BY `id` DESC");
            if(rs.next()){
                String id = rs.getString("id");
                int id1 = Integer.parseInt(id) + 1 ;
                id_lbl.setText(String.valueOf(id1));
                
            }else{
                id_lbl.setText("1");
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        id_lbl = new javax.swing.JLabel();
        bill_txt = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox3 = new javax.swing.JComboBox<>();
        item_txt = new javax.swing.JTextField();
        qty_txt = new javax.swing.JTextField();
        buy_txt = new javax.swing.JTextField();
        sell_txt = new javax.swing.JTextField();
        total_lbl = new javax.swing.JLabel();
        totalbill_lbl = new javax.swing.JLabel();
        addpurchase_btn = new javax.swing.JButton();
        addbill_btn = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        date_lbl = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Add Purchase");
        setResizable(false);

        jPanel1.setPreferredSize(new java.awt.Dimension(900, 845));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("LAKY_COMPUTER SHOP");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 40, 470, 50));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("PURCHASE ID");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, -1, -1));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("BILL NO.");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 110, -1, -1));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("DISTRIBUTOR");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, -1, -1));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("BRAND");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, -1, -1));

        jLabel7.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("MODEL");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 350, -1, -1));

        jLabel8.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("ITEM CODE");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 420, -1, -1));

        jLabel9.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("QTY.");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 470, -1, -1));

        jLabel10.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("BUY PRICE");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 520, -1, -1));

        jLabel11.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("SELL PRICE");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 570, -1, -1));

        jLabel12.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("TOTAL");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 320, -1, -1));

        jLabel13.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("TOTAL BILL");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 460, -1, -1));

        id_lbl.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        id_lbl.setForeground(new java.awt.Color(255, 255, 255));
        id_lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        id_lbl.setText("1");
        id_lbl.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        id_lbl.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(id_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 140, 50));

        bill_txt.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        bill_txt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        bill_txt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        bill_txt.setPreferredSize(new java.awt.Dimension(6, 30));
        jPanel1.add(bill_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 140, 140, 50));

        jComboBox1.setBackground(new java.awt.Color(153, 153, 153));
        jComboBox1.setEditable(true);
        jComboBox1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jComboBox1.setForeground(new java.awt.Color(0, 0, 0));
        jComboBox1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        jComboBox1.setOpaque(false);
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 230, 320, 40));

        jComboBox2.setBackground(new java.awt.Color(153, 153, 153));
        jComboBox2.setEditable(true);
        jComboBox2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jComboBox2.setForeground(new java.awt.Color(0, 0, 0));
        jComboBox2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        jComboBox2.setOpaque(false);
        jPanel1.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 290, 320, 40));

        jComboBox3.setBackground(new java.awt.Color(153, 153, 153));
        jComboBox3.setEditable(true);
        jComboBox3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jComboBox3.setForeground(new java.awt.Color(0, 0, 0));
        jComboBox3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        jComboBox3.setOpaque(false);
        jPanel1.add(jComboBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 350, 320, 40));

        item_txt.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        item_txt.setForeground(new java.awt.Color(255, 255, 255));
        item_txt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        item_txt.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        item_txt.setOpaque(false);
        item_txt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                item_txtMouseClicked(evt);
            }
        });
        jPanel1.add(item_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 410, 320, 40));

        qty_txt.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        qty_txt.setForeground(new java.awt.Color(255, 255, 255));
        qty_txt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        qty_txt.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        qty_txt.setOpaque(false);
        qty_txt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                qty_txtMouseClicked(evt);
            }
        });
        qty_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qty_txtActionPerformed(evt);
            }
        });
        jPanel1.add(qty_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 460, 320, 40));

        buy_txt.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        buy_txt.setForeground(new java.awt.Color(255, 255, 255));
        buy_txt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        buy_txt.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        buy_txt.setOpaque(false);
        buy_txt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buy_txtMouseClicked(evt);
            }
        });
        buy_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                buy_txtKeyReleased(evt);
            }
        });
        jPanel1.add(buy_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 510, 320, 40));

        sell_txt.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        sell_txt.setForeground(new java.awt.Color(255, 255, 255));
        sell_txt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        sell_txt.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        sell_txt.setOpaque(false);
        sell_txt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sell_txtMouseClicked(evt);
            }
        });
        jPanel1.add(sell_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 560, 320, 40));

        total_lbl.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        total_lbl.setForeground(new java.awt.Color(255, 255, 255));
        total_lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        total_lbl.setText("0");
        total_lbl.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        jPanel1.add(total_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 360, 210, 50));

        totalbill_lbl.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        totalbill_lbl.setForeground(new java.awt.Color(255, 255, 255));
        totalbill_lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        totalbill_lbl.setText("0");
        totalbill_lbl.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        jPanel1.add(totalbill_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 510, 210, 50));

        addpurchase_btn.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        addpurchase_btn.setForeground(new java.awt.Color(255, 255, 255));
        addpurchase_btn.setText("ADD PURCHASE");
        addpurchase_btn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 0), 5, true));
        addpurchase_btn.setContentAreaFilled(false);
        addpurchase_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addpurchase_btn.setPreferredSize(new java.awt.Dimension(141, 31));
        addpurchase_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addpurchase_btnActionPerformed(evt);
            }
        });
        jPanel1.add(addpurchase_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 660, 230, 50));

        addbill_btn.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        addbill_btn.setForeground(new java.awt.Color(255, 255, 255));
        addbill_btn.setText("ADD BILL");
        addbill_btn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 51, 0), 5, true));
        addbill_btn.setContentAreaFilled(false);
        addbill_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addbill_btn.setPreferredSize(new java.awt.Dimension(141, 31));
        addbill_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addbill_btnActionPerformed(evt);
            }
        });
        jPanel1.add(addbill_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 660, 220, 50));

        jButton3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("BACK");
        jButton3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        jButton3.setContentAreaFilled(false);
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 740, 150, 45));

        date_lbl.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        date_lbl.setForeground(new java.awt.Color(255, 255, 255));
        date_lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        date_lbl.setText("0000/00/00");
        date_lbl.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        jPanel1.add(date_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, 140, -1));

        jLabel22.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("DATE");
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));

        jLabel14.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("------ ADD PURCHASE -------");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 20, -1, -1));

        jLabel15.setBackground(new java.awt.Color(255, 255, 255));
        jLabel15.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Lakshitha Madushan - Java. All Rights Reserved (c), 2023");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 810, 620, -1));

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/add_purch.png"))); // NOI18N
        jPanel1.add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void qty_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qty_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_qty_txtActionPerformed

    private void buy_txtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_buy_txtKeyReleased
        // TODO add your handling code here:
        int q = Integer.parseInt(qty_txt.getText());
        double b = Double.parseDouble(buy_txt.getText());
        double answer = q * b;
        total_lbl.setText(String.valueOf(answer));
    }//GEN-LAST:event_buy_txtKeyReleased

    private void addpurchase_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addpurchase_btnActionPerformed
        // TODO add your handling code here:
        try {
            String date = date_lbl.getText();
            String bill = bill_txt.getText();
            String dis = jComboBox1.getSelectedItem().toString();
            String brand = jComboBox2.getSelectedItem().toString();
            String model = jComboBox3.getSelectedItem().toString();
            String code = item_txt.getText();
            String qty = qty_txt.getText();
            String buy = buy_txt.getText();
            String sell = sell_txt.getText();
            String total = total_lbl.getText();
            
            dbcon.IUD("INSERT INTO purchase (`date`,`bill_no`,`distributor`,`brand`,`model`,`item_code`,`qty`,`buy`,`sell`,`total`) VALUES ('"+date+"','"+bill+"','"+dis+"','"+brand+"','"+model+"','"+code+"','"+qty+"','"+buy+"','"+sell+"','"+total+"')");
            JOptionPane.showMessageDialog(this, "Purchase Added Succesfully","DONE!",JOptionPane.INFORMATION_MESSAGE);
            
            double total_bill = Double.parseDouble(totalbill_lbl.getText());
            double full_total = Double.parseDouble(total) + total_bill;
            totalbill_lbl.setText(String.valueOf(full_total));
            
            ResultSet rs = dbcon.SEARCH("SELECT * FROM inventory WHERE `item` = '"+model+"'");
            if(rs.next()){
                String id = rs.getString("id");
                int qty1 = Integer.parseInt(rs.getString("qty"));
                int qty2 = Integer.parseInt(qty);
                int qty3 = qty1 + qty2;
                String quantity = String.valueOf(qty3);
                
                dbcon.IUD("UPDATE inventory SET `qty` = '"+quantity+"' WHERE `id` = '"+id+"'");
                JOptionPane.showMessageDialog(this, "Purchase Added Succesfully","DONE!",JOptionPane.INFORMATION_MESSAGE);
            }else{
                dbcon.IUD("INSERT INTO inventory (`item`,`qty`) VALUES ('"+model+"','"+qty+"')");
                JOptionPane.showMessageDialog(this, "Inventory Added Succesfully","DONE!",JOptionPane.INFORMATION_MESSAGE);
            }
                    
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_addpurchase_btnActionPerformed

    private void addbill_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addbill_btnActionPerformed
        // TODO add your handling code here:
        try {
            String date = date_lbl.getText();
            String bill = bill_txt.getText();
            String dis = jComboBox1.getSelectedItem().toString();
            String total = total_lbl.getText();
            String empty = "-";
            dbcon.IUD("INSERT INTO purchase_bill (`date`,`bill`,`distributor`,`total`) VALUES ('"+date+"','"+bill+"','"+dis+"','"+total+"')");
            JOptionPane.showMessageDialog(this, "Purchase Bill Added Succesfully","DONE!",JOptionPane.INFORMATION_MESSAGE); 
            
            dbcon.IUD("INSERT INTO cost (`date`,`bill`,`distributor`,`expence`,`cost`) VALUES ('"+date+"','"+bill+"','"+dis+"','"+empty+"','"+total+"')");
            
            item_txt.setText(null);
            qty_txt.setText(null);
            buy_txt.setText(null);
            sell_txt.setText(null);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_addbill_btnActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        Cashier_Menu cm = new Cashier_Menu();
        cm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void item_txtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_item_txtMouseClicked
        // TODO add your handling code here:
        item_txt.setText(null);
    }//GEN-LAST:event_item_txtMouseClicked

    private void qty_txtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_qty_txtMouseClicked
        // TODO add your handling code here:
        qty_txt.setText(null);
    }//GEN-LAST:event_qty_txtMouseClicked

    private void buy_txtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buy_txtMouseClicked
        // TODO add your handling code here:
        buy_txt.setText(null);
    }//GEN-LAST:event_buy_txtMouseClicked

    private void sell_txtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sell_txtMouseClicked
        // TODO add your handling code here:
        sell_txt.setText(null);
    }//GEN-LAST:event_sell_txtMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Add_Purchase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Add_Purchase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Add_Purchase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Add_Purchase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Add_Purchase().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addbill_btn;
    private javax.swing.JButton addpurchase_btn;
    private javax.swing.JLabel bg;
    private javax.swing.JTextField bill_txt;
    private javax.swing.JTextField buy_txt;
    private javax.swing.JLabel date_lbl;
    private javax.swing.JLabel id_lbl;
    private javax.swing.JTextField item_txt;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField qty_txt;
    private javax.swing.JTextField sell_txt;
    private javax.swing.JLabel total_lbl;
    private javax.swing.JLabel totalbill_lbl;
    // End of variables declaration//GEN-END:variables

public void cbLoadData(String table , String column, JComboBox cb){
    Vector v = new Vector();
    try {
        
        ResultSet rs = dbcon.SEARCH("SELECT * FROM "+table+" ");
        while(rs.next()){
            String col = rs.getString(column);
            v.add(col);
            DefaultComboBoxModel dcm = new DefaultComboBoxModel(v);
            cb.setModel(dcm);
            
        }
        
    } catch (Exception e) {
        e.printStackTrace();
    }
}    
}
