
import java.awt.Image;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author DELL
 */
public final class Add_Sale extends javax.swing.JFrame {

    /**
     * Creates new form Add_Purchase
     */
    public Add_Sale() {
        initComponents();
        
        Image icon = new ImageIcon(this.getClass().getResource("/icon.png")).getImage();
        this.setIconImage(icon);
        
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy/MM/dd");
        Date d = new Date();
        date_lbl.setText(sdf.format(d));
        
        cbLoadData("customer","name", customer_combo);
        AutoCompleteDecorator.decorate(customer_combo);
        
        cbLoadData("brand","name", brand_combo);
        AutoCompleteDecorator.decorate(brand_combo);
        
        cbLoadData("model","name", model_combo);
        AutoCompleteDecorator.decorate(model_combo);
        
        
        try {
            ResultSet rs = dbcon.SEARCH("SELECT `id` FROM sale ORDER BY `id` DESC");
            if(rs.next()){
                String id = rs.getString("id");
                int id1 = Integer.parseInt(id) + 1 ;
                saleId_lbl.setText(String.valueOf(id1));
                
            }else{
                saleId_lbl.setText("1");
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        
        try {
            ResultSet rs = dbcon.SEARCH("SELECT `id` FROM sale_bill ORDER BY `id` DESC");
            if(rs.next()){
                String id = rs.getString("id");
                int id1 = Integer.parseInt(id) + 1 ;
                bill_Id_lbl.setText(String.valueOf(id1));
                
            }else{
                bill_Id_lbl.setText("1");
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        bill_Id_lbl = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        customer_combo = new javax.swing.JComboBox<>();
        brand_combo = new javax.swing.JComboBox<>();
        model_combo = new javax.swing.JComboBox<>();
        code_txt = new javax.swing.JTextField();
        price_txt = new javax.swing.JTextField();
        sell_lbl = new javax.swing.JLabel();
        balance_lbl = new javax.swing.JLabel();
        totalbill_lbl = new javax.swing.JLabel();
        paidAmount_txt = new javax.swing.JTextField();
        addsale_btn = new javax.swing.JButton();
        addbill_btn = new javax.swing.JButton();
        back_btn = new javax.swing.JButton();
        saleId_lbl = new javax.swing.JLabel();
        total_lbl = new javax.swing.JLabel();
        buy_lbl = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        qty_txt = new javax.swing.JTextField();
        date_lbl = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        date_lbl1 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Add Sale");
        setResizable(false);

        jPanel1.setPreferredSize(new java.awt.Dimension(1659, 986));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Arial", 1, 40)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("LAKY_COMPUTER SHOP");
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 20, 500, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("SALE ID");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 140, -1));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("BILL NO.");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 30, 110, 30));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("CUSTOMER");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, -1, -1));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("BRAND");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, -1, -1));

        jLabel7.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("MODEL");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, -1, -1));

        jLabel8.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("ITEM CODE");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, -1, -1));

        jLabel9.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("QTY.");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 380, -1, -1));

        jLabel10.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("PRICE");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 500, -1, -1));

        jLabel11.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("SELL PRICE");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 440, -1, -1));

        jLabel12.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("TOTAL");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 170, -1, -1));

        jLabel13.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("TOTAL BILL");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 170, -1, -1));

        jLabel14.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("PAID AMOUNT");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 430, -1, -1));

        jLabel15.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("BALANCE");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 500, -1, 30));

        jLabel16.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("BILL");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 80, 200, 30));

        bill_Id_lbl.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        bill_Id_lbl.setForeground(new java.awt.Color(255, 255, 255));
        bill_Id_lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bill_Id_lbl.setText("1");
        bill_Id_lbl.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        jPanel1.add(bill_Id_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 30, 140, 40));

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jTextArea1.setForeground(new java.awt.Color(0, 0, 0));
        jTextArea1.setRows(5);
        jTextArea1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 4));
        jTextArea1.setOpaque(false);
        jScrollPane1.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 120, 640, 770));

        customer_combo.setBackground(new java.awt.Color(102, 102, 102));
        customer_combo.setEditable(true);
        customer_combo.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        customer_combo.setForeground(new java.awt.Color(0, 0, 0));
        customer_combo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        customer_combo.setOpaque(false);
        jPanel1.add(customer_combo, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, 369, 40));

        brand_combo.setBackground(new java.awt.Color(102, 102, 102));
        brand_combo.setEditable(true);
        brand_combo.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        brand_combo.setForeground(new java.awt.Color(0, 0, 0));
        brand_combo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        brand_combo.setOpaque(false);
        jPanel1.add(brand_combo, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 190, 369, 40));

        model_combo.setBackground(new java.awt.Color(102, 102, 102));
        model_combo.setEditable(true);
        model_combo.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        model_combo.setForeground(new java.awt.Color(0, 0, 0));
        model_combo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        model_combo.setOpaque(false);
        model_combo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                model_comboActionPerformed(evt);
            }
        });
        jPanel1.add(model_combo, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 250, 369, 40));

        code_txt.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        code_txt.setForeground(new java.awt.Color(255, 255, 255));
        code_txt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        code_txt.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        code_txt.setOpaque(false);
        code_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                code_txtKeyReleased(evt);
            }
        });
        jPanel1.add(code_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 310, 369, 40));

        price_txt.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        price_txt.setForeground(new java.awt.Color(255, 255, 255));
        price_txt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        price_txt.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        price_txt.setOpaque(false);
        price_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                price_txtActionPerformed(evt);
            }
        });
        price_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                price_txtKeyReleased(evt);
            }
        });
        jPanel1.add(price_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 490, 370, 40));

        sell_lbl.setBackground(new java.awt.Color(0, 153, 102));
        sell_lbl.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        sell_lbl.setForeground(new java.awt.Color(255, 255, 255));
        sell_lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sell_lbl.setText("0");
        sell_lbl.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        sell_lbl.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        sell_lbl.setOpaque(true);
        sell_lbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sell_lblMouseClicked(evt);
            }
        });
        jPanel1.add(sell_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 430, 130, 40));

        balance_lbl.setBackground(new java.awt.Color(0, 204, 51));
        balance_lbl.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        balance_lbl.setForeground(new java.awt.Color(255, 255, 255));
        balance_lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        balance_lbl.setText("0");
        balance_lbl.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        balance_lbl.setOpaque(true);
        jPanel1.add(balance_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 490, 220, 50));

        totalbill_lbl.setBackground(new java.awt.Color(51, 51, 255));
        totalbill_lbl.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        totalbill_lbl.setForeground(new java.awt.Color(255, 255, 255));
        totalbill_lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        totalbill_lbl.setText("0");
        totalbill_lbl.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 5, true));
        jPanel1.add(totalbill_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 230, 180, 60));

        paidAmount_txt.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        paidAmount_txt.setForeground(new java.awt.Color(255, 255, 255));
        paidAmount_txt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        paidAmount_txt.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        paidAmount_txt.setOpaque(false);
        paidAmount_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paidAmount_txtActionPerformed(evt);
            }
        });
        paidAmount_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                paidAmount_txtKeyReleased(evt);
            }
        });
        jPanel1.add(paidAmount_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 420, 220, 50));

        addsale_btn.setBackground(new java.awt.Color(255, 102, 51));
        addsale_btn.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        addsale_btn.setForeground(new java.awt.Color(255, 255, 255));
        addsale_btn.setText("ADD SALE");
        addsale_btn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        addsale_btn.setContentAreaFilled(false);
        addsale_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addsale_btn.setOpaque(true);
        addsale_btn.setPreferredSize(new java.awt.Dimension(141, 31));
        addsale_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addsale_btnActionPerformed(evt);
            }
        });
        jPanel1.add(addsale_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 330, 380, 60));

        addbill_btn.setBackground(new java.awt.Color(204, 0, 0));
        addbill_btn.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        addbill_btn.setForeground(new java.awt.Color(255, 255, 255));
        addbill_btn.setText("ADD BILL");
        addbill_btn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        addbill_btn.setContentAreaFilled(false);
        addbill_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addbill_btn.setOpaque(true);
        addbill_btn.setPreferredSize(new java.awt.Dimension(141, 31));
        addbill_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addbill_btnActionPerformed(evt);
            }
        });
        jPanel1.add(addbill_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 910, 340, 60));

        back_btn.setBackground(new java.awt.Color(153, 153, 153));
        back_btn.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        back_btn.setForeground(new java.awt.Color(255, 255, 255));
        back_btn.setText("BACK");
        back_btn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        back_btn.setContentAreaFilled(false);
        back_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        back_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_btnActionPerformed(evt);
            }
        });
        jPanel1.add(back_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 920, 150, 45));

        saleId_lbl.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        saleId_lbl.setForeground(new java.awt.Color(255, 255, 255));
        saleId_lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        saleId_lbl.setText("1");
        saleId_lbl.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        jPanel1.add(saleId_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 30, 140, 40));

        total_lbl.setBackground(new java.awt.Color(102, 102, 255));
        total_lbl.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        total_lbl.setForeground(new java.awt.Color(255, 255, 255));
        total_lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        total_lbl.setText("0");
        total_lbl.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 5, true));
        jPanel1.add(total_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 230, 170, 60));

        buy_lbl.setBackground(new java.awt.Color(0, 153, 102));
        buy_lbl.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        buy_lbl.setForeground(new java.awt.Color(255, 255, 255));
        buy_lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        buy_lbl.setText("0");
        buy_lbl.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        buy_lbl.setOpaque(true);
        jPanel1.add(buy_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 430, 120, 40));

        jLabel24.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setText("BUY PRICE");
        jPanel1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 440, -1, -1));

        qty_txt.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        qty_txt.setForeground(new java.awt.Color(255, 255, 255));
        qty_txt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        qty_txt.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        qty_txt.setOpaque(false);
        qty_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qty_txtActionPerformed(evt);
            }
        });
        jPanel1.add(qty_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 370, 369, 40));

        date_lbl.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        date_lbl.setForeground(new java.awt.Color(255, 255, 255));
        date_lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        date_lbl.setText("0000/00/00");
        date_lbl.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jPanel1.add(date_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(1280, 20, 200, 50));

        jLabel26.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("DATE");
        jPanel1.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 20, -1, 40));

        jTable1.setBackground(new java.awt.Color(102, 102, 102));
        jTable1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jTable1.setForeground(new java.awt.Color(255, 255, 255));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "BRAND", "MODEL", "ITEM CODE", "QTY", "PRICE", "TOTAL"
            }
        ));
        jTable1.setGridColor(new java.awt.Color(255, 255, 255));
        jTable1.setOpaque(false);
        jTable1.setRowHeight(28);
        jTable1.setRowMargin(5);
        jScrollPane2.setViewportView(jTable1);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 570, 940, 320));

        date_lbl1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        date_lbl1.setForeground(new java.awt.Color(255, 255, 255));
        date_lbl1.setText("----- ADD SALE -----");
        jPanel1.add(date_lbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1510, 20, -1, 30));

        jLabel17.setBackground(new java.awt.Color(255, 255, 255));
        jLabel17.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("Lakshitha Madushan - Java. All Rights Reserved (c), 2023");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 950, 620, -1));

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/add_sale.png"))); // NOI18N
        jPanel1.add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void price_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_price_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_price_txtActionPerformed

    private void qty_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qty_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_qty_txtActionPerformed

    private void price_txtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_price_txtKeyReleased
        // TODO add your handling code here:
        int q = Integer.parseInt(qty_txt.getText());
        double b = Double.parseDouble(price_txt.getText());
        double answer = q * b;
        total_lbl.setText(String.valueOf(answer));
    }//GEN-LAST:event_price_txtKeyReleased

    private void paidAmount_txtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_paidAmount_txtKeyReleased
        // TODO add your handling code here:
        double bill = Double.parseDouble(totalbill_lbl.getText());
        int pay = Integer.parseInt(paidAmount_txt.getText());
        double balance = pay - bill;
        balance_lbl.setText(String.valueOf(balance));
        
    }//GEN-LAST:event_paidAmount_txtKeyReleased

    private void addsale_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addsale_btnActionPerformed
        // TODO add your handling code here:
        try {
            String date = date_lbl.getText();
            String bill = bill_Id_lbl.getText();
            String cus = customer_combo.getSelectedItem().toString();
            String brand = brand_combo.getSelectedItem().toString();
            String model = model_combo.getSelectedItem().toString();
            String item = code_txt.getText();
            String qty = qty_txt.getText();
            String buy = buy_lbl.getText();
            String sell = sell_lbl.getText();
            String price = price_txt.getText();
            String total = total_lbl.getText();
            
                      
            dbcon.IUD("INSERT INTO sale (`date`,`bill_no`,`customer`,`brand`,`model`,`item_code`,`qty`,`buy`,`sell`,`price`,`total`) VALUES ('"+date+"','"+bill+"','"+cus+"','"+brand+"','"+model+"','"+item+"','"+qty+"','"+buy+"','"+sell+"','"+price+"','"+total+"')");
            JOptionPane.showMessageDialog(this, "Sales Added Succesfully","DONE!",JOptionPane.INFORMATION_MESSAGE);
            
            
            ResultSet rs = dbcon.SEARCH("SELECT * FROM inventory WHERE `item` = '"+model+"' ");
            rs.next();
            String id = rs.getString("id");
            int qty1 = Integer.parseInt(rs.getString("qty"));
            int qty2 = Integer.parseInt(qty);
            int qty3 = qty1 - qty2;
            dbcon.IUD("UPDATE inventory SET `qty` = '"+String.valueOf(qty3)+"' WHERE `id` = '"+id+"' ");
            JOptionPane.showMessageDialog(this, "Inventory Reduce Succesfully","DONE!",JOptionPane.INFORMATION_MESSAGE);
                                           
            double total_bill = Double.parseDouble(totalbill_lbl.getText());
            double full_total = Double.parseDouble(total) + total_bill;
            totalbill_lbl.setText(String.valueOf(full_total));
            
            //add details to table
            DefaultTableModel dtm =(DefaultTableModel)jTable1.getModel();
            String sid = saleId_lbl.getText();
            dtm.insertRow(dtm.getRowCount(), new Object[]{sid, brand , model, item, qty, price, total } );
            
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_addsale_btnActionPerformed

    private void model_comboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_model_comboActionPerformed
        // TODO add your handling code here:
        try {
            String item = model_combo.getSelectedItem().toString();
            ResultSet rs = dbcon.SEARCH("SELECT * FROM purchase WHERE `model` = '"+item+"'");
            rs.next();
            String brand = rs.getString("brand");
            String code = rs.getString("item_code");
            String buy = rs.getString("buy");
            String sell = rs.getString("sell");
            String price = rs.getString("sell");
            brand_combo.setSelectedItem(brand);
            code_txt.setText(code);
            buy_lbl.setText(buy);
            sell_lbl.setText(sell);
            price_txt.setText(price);
        
        } catch (Exception e) {
        e.printStackTrace();
        }
    }//GEN-LAST:event_model_comboActionPerformed

    private void code_txtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_code_txtKeyReleased
        // TODO add your handling code here:
         try {
            String code = code_txt.getText();
            ResultSet rs = dbcon.SEARCH("SELECT * FROM purchase WHERE `item_code` = '"+code+"'");
            rs.next();
            String brand = rs.getString("brand");
            String model = rs.getString("model");
            String buy = rs.getString("buy");
            String sell = rs.getString("sell");
            String price = rs.getString("sell");
            brand_combo.setSelectedItem(brand);
            model_combo.setSelectedItem(model);
            buy_lbl.setText(buy);
            sell_lbl.setText(sell);
            price_txt.setText(price);
        
        } catch (Exception e) {
        e.printStackTrace();
        }
    }//GEN-LAST:event_code_txtKeyReleased

    private void addbill_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addbill_btnActionPerformed
        // TODO add your handling code here:
        try {
            String date = date_lbl.getText();
            String bill = bill_Id_lbl.getText();
            String cus = customer_combo.getSelectedItem().toString();
            String total = total_lbl.getText();
            
            dbcon.IUD("INSERT INTO sale_bill (`date`,`bill`,`customer`,`total`) VALUES ('"+date+"','"+bill+"','"+cus+"','"+total+"')");
            dbcon.IUD("INSERT INTO income (`date`,`bill`,`customer`,`income`) VALUES ('"+date+"','"+bill+"','"+cus+"','"+total+"')");
            JOptionPane.showMessageDialog(this, "Sale Bill and Income Added Succesfully","DONE!",JOptionPane.INFORMATION_MESSAGE);
            
            // Bill create
            
            jTextArea1.setText(jTextArea1.getText()+ "#############**********################********#############*******###############........#######"+"\n"+ "\n");
            jTextArea1.setText(jTextArea1.getText()+ "\t" + "................................DIGIMAX MOBILE............................................" + "\n");
            jTextArea1.setText(jTextArea1.getText()+ "\t" + "................................Galle Dangedara..........................................." + "\n");
            jTextArea1.setText(jTextArea1.getText()+ "\t" + "..................................0703927563.............................................." + "\n");
            jTextArea1.setText(jTextArea1.getText()+ "\t" + "..............................lak1701201@gmail.com........................................" + "\n"+ "\n");
            jTextArea1.setText(jTextArea1.getText()+ "#############**********################********#############*******###############........#######"+"\n"+ "\n");
            jTextArea1.setText(jTextArea1.getText()+ "\t" + "....... DATE     :- "+date+"" + "\n");
            jTextArea1.setText(jTextArea1.getText()+ "\t" + "....... BILL NO  :- "+bill+"" + "\n");
            jTextArea1.setText(jTextArea1.getText()+ "\t" + "....... CUSTOMER :- "+cus+"" + "\n"+ "\n");
            jTextArea1.setText(jTextArea1.getText()+ "#############**********################********#############*******###############........#######"+"\n"+ "\n"+ "\n");
            jTextArea1.setText(jTextArea1.getText()+ "SALE ID"+"\t"+"BRAND"+"\t"+"MODEL"+"\t"+"CODE"+"\t"+"QTY"+"\t"+"PRICE"+"\t"+"TOTAL"+"\n"+"\n");
            
            for(int r = 0;r<jTable1.getRowCount();r++){
                String i = jTable1.getValueAt(r,0).toString();
                String b = jTable1.getValueAt(r,1).toString();
                String m = jTable1.getValueAt(r,2).toString();
                String c = jTable1.getValueAt(r,3).toString();
                String q = jTable1.getValueAt(r,4).toString();
                String p = jTable1.getValueAt(r,5).toString();
                String t = jTable1.getValueAt(r,6).toString();
                jTextArea1.setText(jTextArea1.getText()+i+"\t"+b+"\t"+m+"\t"+c+"\t"+q+"\t"+p+"\t"+t+"\n");                
            }
            
            jTextArea1.setText(jTextArea1.getText()+ "\t"+"........ GROSE TOTAL :- "+"\t"+totalbill_lbl.getText()+"\n");
            jTextArea1.setText(jTextArea1.getText()+ "\t"+"........ PAYMENT     :- "+"\t"+paidAmount_txt.getText()+ "\n");
            jTextArea1.setText(jTextArea1.getText()+ "\t"+"........ BALANC      :- "+"\t"+balance_lbl.getText()+ "\n"+ "\n");
            jTextArea1.setText(jTextArea1.getText()+ "#############**********################********#############*******###############........#######"+"\n");
            jTextArea1.setText(jTextArea1.getText()+ "\t"+"....................................SIGNATURE..............................................." + "\n"+ "\n");
            jTextArea1.setText(jTextArea1.getText()+ "*************************************************************************************************"+"\n"+ "\n");
            jTextArea1.setText(jTextArea1.getText()+ "\t"+"....................................THANK YOU..............................................."+"\n"+ "\n");
            jTextArea1.setText(jTextArea1.getText()+ "\t"+"...................................COME AGAIN..............................................."+"\n"+ "\n");
            jTextArea1.setText(jTextArea1.getText()+ " ..........  LAKSHITHA MADUSHAN @ SOFTWARE ENGINEER - JAVA DEVELOPER!!! ALL RIGHT (C)  .........."+"\n"+"\n");
            jTextArea1.setText(jTextArea1.getText()+ "#############**********################********#############*******###############........#######");
            
            jTextArea1.print();
            
            
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_addbill_btnActionPerformed

    private void back_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_btnActionPerformed
        // TODO add your handling code here:
        Cashier_Menu cm = new Cashier_Menu();
        cm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_back_btnActionPerformed

    private void paidAmount_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paidAmount_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_paidAmount_txtActionPerformed

    private void sell_lblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sell_lblMouseClicked
        // TODO add your handling code here:
//        String a =sell_lbl.getText();
//        price_txt.setText(a);
    }//GEN-LAST:event_sell_lblMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Add_Purchase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Add_Purchase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Add_Purchase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Add_Purchase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Add_Purchase().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addbill_btn;
    private javax.swing.JButton addsale_btn;
    private javax.swing.JButton back_btn;
    private javax.swing.JLabel balance_lbl;
    private javax.swing.JLabel bg;
    private javax.swing.JLabel bill_Id_lbl;
    private javax.swing.JComboBox<String> brand_combo;
    private javax.swing.JLabel buy_lbl;
    private javax.swing.JTextField code_txt;
    private javax.swing.JComboBox<String> customer_combo;
    private javax.swing.JLabel date_lbl;
    private javax.swing.JLabel date_lbl1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JComboBox<String> model_combo;
    private javax.swing.JTextField paidAmount_txt;
    private javax.swing.JTextField price_txt;
    private javax.swing.JTextField qty_txt;
    private javax.swing.JLabel saleId_lbl;
    private javax.swing.JLabel sell_lbl;
    private javax.swing.JLabel total_lbl;
    private javax.swing.JLabel totalbill_lbl;
    // End of variables declaration//GEN-END:variables


public void cbLoadData(String table , String column, JComboBox cb){
    Vector v = new Vector();
    try {
        
        ResultSet rs = dbcon.SEARCH("SELECT * FROM "+table+" ");
        while(rs.next()){
            String col = rs.getString(column);
            v.add(col);
            DefaultComboBoxModel dcm = new DefaultComboBoxModel(v);
            cb.setModel(dcm);
            
        }
        
    } catch (Exception e) {
        e.printStackTrace();
    }
}    
}
