
import java.awt.Image;
import javax.swing.ImageIcon;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author DELL
 */
public class Cashier_Menu extends javax.swing.JFrame {

    /**
     * Creates new form Owner_Menu
     */
    public Cashier_Menu() {
        initComponents();
        
        Image icon = new ImageIcon(this.getClass().getResource("/icon.png")).getImage();
        this.setIconImage(icon);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        componets_btn = new javax.swing.JButton();
        purchase_btn = new javax.swing.JButton();
        sale_btn = new javax.swing.JButton();
        banking_btn = new javax.swing.JButton();
        expences_btn = new javax.swing.JButton();
        back_btn = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cashier Menu");
        setResizable(false);

        jPanel1.setPreferredSize(new java.awt.Dimension(600, 700));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("LAKY_COMPUTER SHOP");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 50, 450, -1));

        componets_btn.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        componets_btn.setForeground(new java.awt.Color(255, 255, 255));
        componets_btn.setText("ADD COMPONENTS");
        componets_btn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        componets_btn.setContentAreaFilled(false);
        componets_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        componets_btn.setPreferredSize(new java.awt.Dimension(141, 31));
        componets_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                componets_btnActionPerformed(evt);
            }
        });
        jPanel1.add(componets_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 310, 60));

        purchase_btn.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        purchase_btn.setForeground(new java.awt.Color(255, 255, 255));
        purchase_btn.setText("ADD PURCHASE");
        purchase_btn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        purchase_btn.setContentAreaFilled(false);
        purchase_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        purchase_btn.setPreferredSize(new java.awt.Dimension(141, 31));
        purchase_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                purchase_btnActionPerformed(evt);
            }
        });
        jPanel1.add(purchase_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 270, 310, 60));

        sale_btn.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        sale_btn.setForeground(new java.awt.Color(255, 255, 255));
        sale_btn.setText("ADD SALE");
        sale_btn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 5));
        sale_btn.setContentAreaFilled(false);
        sale_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sale_btn.setPreferredSize(new java.awt.Dimension(141, 31));
        sale_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sale_btnActionPerformed(evt);
            }
        });
        jPanel1.add(sale_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 390, 330, 80));

        banking_btn.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        banking_btn.setForeground(new java.awt.Color(255, 255, 255));
        banking_btn.setText("ADD BANKING");
        banking_btn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        banking_btn.setContentAreaFilled(false);
        banking_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        banking_btn.setPreferredSize(new java.awt.Dimension(141, 31));
        banking_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                banking_btnActionPerformed(evt);
            }
        });
        jPanel1.add(banking_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 640, 310, 60));

        expences_btn.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        expences_btn.setForeground(new java.awt.Color(255, 255, 255));
        expences_btn.setText("ADD EXPENCES");
        expences_btn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        expences_btn.setContentAreaFilled(false);
        expences_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        expences_btn.setPreferredSize(new java.awt.Dimension(141, 31));
        expences_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                expences_btnActionPerformed(evt);
            }
        });
        jPanel1.add(expences_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 520, 310, 60));

        back_btn.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        back_btn.setForeground(new java.awt.Color(255, 255, 255));
        back_btn.setText("BACK");
        back_btn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 4, true));
        back_btn.setContentAreaFilled(false);
        back_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        back_btn.setPreferredSize(new java.awt.Dimension(141, 31));
        back_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_btnActionPerformed(evt);
            }
        });
        jPanel1.add(back_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 710, 140, 60));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("------ CASHIER MENU ------");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 20, -1, -1));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Lakshitha Madushan - Java. All Rights Reserved (c), 2023");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 790, 620, -1));

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/owner1.png"))); // NOI18N
        jPanel1.add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 790, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 834, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void componets_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_componets_btnActionPerformed
        // TODO add your handling code here:
        Add_Component c = new Add_Component();
        c.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_componets_btnActionPerformed

    private void purchase_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_purchase_btnActionPerformed
        // TODO add your handling code here:
        Add_Purchase p = new Add_Purchase();
        p.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_purchase_btnActionPerformed

    private void sale_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sale_btnActionPerformed
        // TODO add your handling code here:
        Add_Sale s = new Add_Sale();
        s.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_sale_btnActionPerformed

    private void banking_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_banking_btnActionPerformed
        // TODO add your handling code here:
        Add_Banking b = new Add_Banking();
        b.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_banking_btnActionPerformed

    private void expences_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_expences_btnActionPerformed
        // TODO add your handling code here:
        Add_Expences e = new Add_Expences();
        e.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_expences_btnActionPerformed

    private void back_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_btnActionPerformed
        // TODO add your handling code here:
        Login l =new Login();
        l.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_back_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Owner_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Owner_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Owner_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Owner_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Owner_Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back_btn;
    private javax.swing.JButton banking_btn;
    private javax.swing.JLabel bg;
    private javax.swing.JButton componets_btn;
    private javax.swing.JButton expences_btn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton purchase_btn;
    private javax.swing.JButton sale_btn;
    // End of variables declaration//GEN-END:variables
}
